apiVersion: v1
kind: Service
metadata:
  name: mediplus-service
  namespace: mediplus
  labels:
    app: mediplus
spec:
  type: NodePort
  selector:
    app: mediplus
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
